services:
  db:
    image: postgres:15
    container_name: my-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: my-db
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-store:
